Repository DmytroKolisnyk2/audioCatalogAPI, pull requests merged in 2022-10, with the labels that each got.

#3 Feature/graceful shutdown
  src/server.ts
  src/utils/graceful-shutdown.ts
  src/utils/index.ts
Labels: documentation, enhancement

#8 #20: changed gracefulShutdown function to class
  src/server.ts
  src/utils/graceful-shutdown.ts
Labels: enhancement

#15 fixed build settings
  package.json
Labels: root

#12 Feature/cloudinary
  example.env
  package-lock.json
  package.json
  src/app.ts
  src/common/enums/files.ts
  src/common/enums/index.ts
  src/utils/cloudinary-config.ts
  src/utils/index.ts
  src/utils/multer-config.ts
Labels: root, backend

#16 # 13: added release check
  .github/workflows/release.yml
Labels: CI/CD

#13 Feature/authorization
  locales/en/auth.json
  locales/ua/auth.json
  package-lock.json
  package.json
  src/app.ts
  src/common/constants/auth-validation.ts
  src/common/constants/index.ts
  src/common/constants/jwt-config.ts
  src/common/enums/auth-routes.ts
  src/common/enums/statuses.ts
  src/common/types/JwtPayload/index.ts
  src/common/types/global.d.ts
  src/common/types/index.ts
  src/common/types/initialization/index.ts
  src/common/types/user/index.ts
  src/db/config/jwtStrategy/index.ts
  src/db/config/jwtStrategy/jwtStrategy.ts
  src/db/models/index.ts
  src/db/models/user.model.ts
  src/error/index.ts
  src/error/invalidPassword.error.ts
  src/error/notExistUser.error.ts
  src/error/unAuthorized.error.ts
  src/error/username-exist.error.ts
  src/middlewares/auth.middleware.ts
  src/middlewares/error-handler.middleware.ts
  src/middlewares/index.ts
  src/middlewares/joi-schema-validation.middleware.ts
  src/middlewares/localization.middleware.ts
  src/repositories/index.ts
  src/repositories/user.repository.ts
  src/routes/auth.routes.ts
  src/routes/test.routes.ts
  src/services/auth.service.ts
  src/services/index.ts
  src/utils/index.ts
  src/utils/jwtToken.ts
  src/validation/auth.schema.ts
  src/validation/index.ts
Labels: root, backend

#17 # 7: updated docs
  src/app.ts
  src/common/enums/api-routes.ts
  src/docs/api.json
Labels: backend

#18 #29: fixed cloudinary export
  src/app.ts
  src/utils/cloudinary-config.ts
Labels: backend

#19 # 15: added creating of audio
  .gitignore
  locales/en/audio.json
  locales/ua/audio.json
  package-lock.json
  public/uploads/.gitkeep
  src/common/constants/audio-config.ts
  src/common/constants/file-size-config.ts
  src/common/constants/index.ts
  src/common/enums/files-fields.ts
  src/common/enums/files.ts
  src/common/enums/index.ts
  src/common/enums/models.ts
  src/common/enums/refs.ts
  src/common/types/audio/index.ts
  src/common/types/cloudinary/index.ts
  src/common/types/express.d.ts
  src/common/types/index.ts
  src/common/types/initialization/index.ts
  src/common/types/user/index.ts
  src/db/models/audio.model.ts
  src/db/models/index.ts
  src/db/models/playlist.model.ts
  src/db/models/profile.model.ts
  src/db/models/test.model.ts
  src/db/models/user.model.ts
  src/error/audio-size.error.ts
  src/error/cover-size.error.ts
  src/error/genres-not-valid.error.ts
  src/error/index.ts
  src/error/invalid-password.error.ts
  src/error/unauthorized.error.ts
  src/error/user-not-exist.error.ts
  src/error/wrong-audio-format.error.ts
  src/error/wrong-image-format.error.ts
  src/helpers/enum-includes.ts
  src/helpers/index.ts
  src/middlewares/auth.middleware.ts
  src/middlewares/index.ts
  src/middlewares/localization.middleware.ts
  src/middlewares/parse-genres.middleware.ts
  src/middlewares/upload-audio-files.middleware.ts
  src/repositories/audio.repository.ts
  src/repositories/index.ts
  src/routes/audio.routes.ts
  src/routes/auth.routes.ts
  src/services/audio.service.ts
  src/services/auth.service.ts
  src/services/cloudinary.service.ts
  src/services/index.ts
  src/utils/cloudinary-config.ts
  src/utils/index.ts
  src/utils/multer-config.ts
  src/validation/audio.schema.ts
Labels: root, backend

#20 # 15: fixed relation
  src/repositories/audio.repository.ts
  src/repositories/index.ts
Labels: backend

#21 Features/get users routes
  locales/en/user.json
  locales/ua/user.json
  src/common/enums/api-routes.ts
  src/common/enums/index.ts
  src/common/enums/users-routes.ts
  src/common/types/initialization/index.ts
  src/common/types/user/index.ts
  src/db/models/user.model.ts
  src/error/index.ts
  src/error/user-not-found.error.ts
  src/middlewares/localization.middleware.ts
  src/repositories/user.repository.ts
  src/routes/index.ts
  src/routes/users.routes.ts
  src/services/auth.service.ts
  src/services/index.ts
  src/services/users.service.ts
Labels: backend

#22 # 26: added get route
  locales/en/audio.json
  locales/ua/audio.json
  src/common/enums/audio-routes.ts
  src/error/audio-not-found.ts
  src/error/index.ts
  src/middlewares/index.ts
  src/middlewares/non-strict-auth.middleware.ts
  src/repositories/audio.repository.ts
  src/routes/audio.routes.ts
  src/services/audio.service.ts
Labels: backend

#23 # 33: Added /audios, /audios/new, audios/top
  src/common/enums/audio-routes.ts
  src/repositories/audio.repository.ts
  src/routes/audio.routes.ts
  src/services/audio.service.ts
Labels: backend

#24 # 25: added route
  package-lock.json
  package.json
  src/common/enums/audio-routes.ts
  src/repositories/audio.repository.ts
  src/routes/audio.routes.ts
  src/services/audio.service.ts
Labels: root, backend

#25 # 37: fixed script
  package.json
Labels: root

#26 # 23: added toggle follow route
  src/common/enums/users-routes.ts
  src/repositories/user.repository.ts
  src/routes/users.routes.ts
  src/services/users.service.ts
Labels: backend

#28 Fix/bugs
  src/app.ts
  src/common/enums/api-routes.ts
  src/common/types/index.ts
  src/common/types/initialization/index.ts
  src/common/types/profile/index.ts
  src/common/types/test/index.ts
  src/db/config/jwtStrategy/jwtStrategy.ts
  src/db/models/index.ts
  src/db/models/profile.model.ts
  src/db/models/test.model.ts
  src/db/models/user.model.ts
  src/repositories/index.ts
  src/repositories/test.repository.ts
  src/repositories/user.repository.ts
  src/routes/index.ts
  src/routes/test.routes.ts
  src/services/index.ts
  src/services/test.service.ts
Labels: backend

#29 Fix/populate profile
  src/repositories/user.repository.ts
Labels: backend

#31 Features/put users
  locales/en/auth.json
  locales/en/test.json
  locales/en/user.json
  locales/ua/auth.json
  locales/ua/test.json
  locales/ua/user.json
  src/common/enums/statuses.ts
  src/common/enums/users-routes.ts
  src/common/types/initialization/index.ts
  src/common/types/profile/index.ts
  src/db/models/profile.model.ts
  src/error/access-forbidden.error.ts
  src/error/index.ts
  src/repositories/index.ts
  src/repositories/profile.repository.ts
  src/routes/users.routes.ts
  src/services/index.ts
  src/services/profile.service.ts
  src/services/users.service.ts
  src/validation/index.ts
  src/validation/profile.schema.ts
  src/validation/test.schema.ts
Labels: backend

#27 #31 bannerPatch
  src/common/enums/users-routes.ts
  src/common/types/initialization/index.ts
  src/db/models/profile.model.ts
  src/repositories/index.ts
  src/repositories/profile.repository.ts
  src/routes/users.routes.ts
  src/services/index.ts
  src/services/profile.service.ts
Labels: backend
